### PR TITLE
Update proximity speed & imports, fix #6 and `/rsmp` tab

### LINKED ISSUE #6: Add radius for revive sound
### What and How?

Add a radius (around 100 blocks maybe) for the revive sound.

### Why?

It can be very annoying, especially when there are a lot of undead being revived (like when CommandGeek is streaming).

### Are there alternatives?

Muting my game, but it would still affect other players

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by srnyx**
## Description
- Proximity speed for undeads will now be given when another player is not a radius of 50 blocks (instead of 100) and will only get speed 3 instead of 5.
- Revive sound will now only be heard by the killer and the killed.
- `/rsmp` will no longer break placeholders in tab

Co-authored by: @DWAA1660 

## Motivation and Context
Fixes #6

## How Has This Been Tested?
Tested on a test server on Java 1.17.1, Paper

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to [the documentation](https://github.com/commandgeek/geeksmp/wiki).
- [x] I have read the [**CONTRIBUTING**](https://github.com/commandgeek/geeksmp/blob/master/.github/CONTRIBUTING.md) document.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Lianecx** [comment]
But why only speed 3. I see no reason for that. They cant even use elytra anymore

**Comment by srnyx** [comment]
> But why only speed 3. I see no reason for that. They cant even use elytra anymore

Zombies are supposed to be slow. It makes no sense for them to be faster than normal speed...

**Comment by Lianecx** [comment]
They are supposed to be faster thab normal players.  They should be able to get to other players quickly

**Comment by srnyx** [comment]
> They are supposed to be faster thab normal players. They should be able to get to other players quickly

No, they aren't... they are undead...
Last time I checked bones and brainless creatures don't move faster than muscles and brains.

**Comment by DWAA1660** [comment]
skeles still get speed 5 all the time right

**Comment by Lianecx** [comment]
Skeles also only have speed 3 now

**Comment by srnyx** [comment]
> Skeles also only have speed 3 now

Yeah, but that's still faster than normal players.
The only noticeable difference is with zombies. But they still run faster than usual.

**Comment by srnyx** [comment]
Since the imports change lists basically every file as changed, here's the important changes I made:
image
image
image

**Review by commandgeek — APPROVED** [review]

**Pull request merged**
