### PR TITLE
Undead adventure mode, iron golems fix, remove pets

### LINKED ISSUE #47: Undead boat issue
### Expected behavior

The boat should either be placed or not be placed. 

### Actual behavior

The boat may place if an undead spams fast enough or if the undead is jumping and spamming the boat is summoned. 

### Steps to reproduce

To do it by just spamming:
1. Be undead
2. A bit in front of you so the boat has space to spawn
3. Spam rmb as fast as you can 

To do it by running and jumping:
P.S. I found this when on my way to the gold farm as undead. I was hopping on the ice blocks clicking the ice with a boat in my hand
1. Be undead
2. Run forward while jumping
3. Spam boat below you when you are in the air

### Minecraft version and OS

The server version

### Checks

- [X] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

The tests I did were on land but Datnip did one as well and it worked on the water. Datnip also said it happens when an undead places the boat in the same tick that they jump.

### LINKED ISSUE #48: Iron golems and undeads
### Expected behavior

Since undeads are either zombies or skeletons iron golems should move towards and damage them like when a player hits a golem. 

### Actual behavior

Iron golems go to the undead and attack, but it doesn’t do any damage. 

### Steps to reproduce

1. Be undead
2. Stand around iron golem
3. Observe

### Minecraft version and OS

Server version

### Checks

- [X] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

https://media.discordapp.net/attachments/882211454437179392/923390026790875146/unknown.png

### PR DESCRIPTION
**Pull request by Lianecx**
- Make undeads be in adventure mode.
- Iron golems and tridents DO damage to undeads
- Fixes #48.
- Solution to #53 (Conversation will stay open)
- Removes pets

### CODE REVIEW

**Review by srnyx — COMMENTED** [review]
Will the gamemode be changed to survival when they become alive?

**Comment by DWAA1660** [comment]
did you just completely remove pets :/

**Comment by Lianecx** [comment]
I think so lol, gonna fix that tmr

**Comment by Lianecx** [comment]
Commits are a little confusing, sry about that

**Comment by srnyx** [comment]
> did you just completely remove pets :/

Oh yeah, that seems to be an issue then. But we are considering removing pets anyway.
So @Lianecx since it's not possible to implement pets with adventure mode just remove pets entirely.
If we decide we don't want pets, we'll merge. If we want to keep pets we'll close.

**Comment by Lianecx** [comment]
Exactly thats what i was gonna do. Set then to survuival mode as soon as they get in range

**Comment by Lianecx** [comment]
So tell me if i should implement that or just remove then

**Comment by Lianecx** [comment]
So what about the pets?

**Comment by srnyx** [comment]
> So what about the pets?

We've decided to remove entirely

**Comment by Lianecx** [comment]
Okay so should i remove them?

**Comment by srnyx** [comment]
> Okay so should i remove them?

Yes...

**Comment by Lianecx** [comment]
I removed the `pet` command. I don't really want to remove any code, I leave that to commandgeek

**Review by srnyx — APPROVED** [review]

**Review by commandgeek — APPROVED** [review]

**Pull request merged**
