### PR TITLE
Fix #8, #11, #15, #37, #51, #56, #57, #70, #71, #88, #93-#96, and other changes

### LINKED ISSUE #8: Blacklisted Words - Format Code K
### What and How?

For blacklisted words such as curses, or slurs, have them covered automatically by format code `K` in-game instead of `*****`

### Why?

There is no specific reason for this, it just makes things look easier, and makes it easier for staff to identify swears and not people just spamming `****` for no reason in particular.

java_pZzWrWpbTR

### Are there alternatives?

I do not know of any other alternative to this, that would cover it nicely and be easily identifiable as a swear by staff. 
Feel free to create something different.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

_No response_

### LINKED ISSUE #11: `/reason` doesn't work
### Expected behavior

`/reason` should work

### Actual behavior

`/reason` doesn't work

### Steps to reproduce

Use `/reason`

### Minecraft version and OS

1.17.1, Windows 10

### Checks

- [ ] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

Error in console when running command (`/reason <punished user>`, `/reason <punished user> <reason>` says `Invalid arguments` and nothing happens): https://paste.srnyx.xyz/kipabajaro.properties

### LINKED ISSUE #15: Staff Viewing Trust-Lists
### What and How?

A command for staff to view specific users trusts lists.

For example /trustlistsee <user>
Would display:

image

### Why?

This should be implemented to staff can view specific users trusts lists for moderation intentions.

Scenario:
Someone could have removed something from a players chest and the missing item is reported

Staff can then check that chest, see the user that took the item, and then view if that user is apart of the reporters trust list without having a need for them to be online at the time.

### Are there alternatives?

No.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

_No response_

### LINKED ISSUE #37: Skeleton undeads can farm arrows/bows
### Expected behavior

- Skeleton bows/arrow shouldn't be dropped on death.
- Arrows shouldn't be able to be picked up from skeleton undead's bow shots

### Actual behavior

- Skeleton bows/arrow drop on each death
- Arrows can be picked up if it's stuck in the ground when shot by a skeleton undead

### Steps to reproduce

-
1. Become skeleton undead
2. Die
3. Go to death location
4. Pick up bow

-
1. Become skeleton undead
2. Shoot an arrow
3. Pick up arrow

### Minecraft version and OS

1.18.1, Windows 10

### Checks

- [X] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

_No response_

### LINKED ISSUE #51: Effect disappeares upon relog
### Expected behavior

When you leave and rejoin you keep the potion effects you had before you left. 

### Actual behavior

When you relog you lose the effect(s) you had before you left. 

### Steps to reproduce

1. Have an effect
2. Disconnect
3. Reconnect
4. Effect gone

### Minecraft version and OS

1.17.1, Windows 10

### Checks

- [X] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

I found this while trying to start a raid. I got bad omen from Biancas house and was going to the place I wanted to do the raid. I had to disconnect for a minute and when I rejoined I realized I did not have bad omen anymore. I asked in the discord and Datnip verified this is a bug.

### LINKED ISSUE #56: Make player invulnerable when AFK
### What and How?

When a user is AFK make it so they can't take damage from mobs/players.

### Why?

If you suddenly have to go AFK an undead, another alive player, or mobs can come and kill you. Then your stuff will despawn or be taken.

### Are there alternatives?

Leaving the server instead of going AFK.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

_No response_

### LINKED ISSUE #57: Prefix/suffix/chat format improvements
### What and How?

Instead of setting a different chat format for each rank, just have one chat format (with the ability to set specific ones [specific ones overwrite global]) and use placeholders like `%prefix%`, `%suffix%`, `%chatcolor%`, etc...

### Why?

Right now if you want to change even one thing about the chat format you have to change every `chat-format` for every rank. Same with prefixes.

### Are there alternatives?

Keep the current system

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

_No response_

### LINKED ISSUE #70: Undead bypass locked pressure plates
### Expected behavior

Undeads shouldn't be able to use locked pressure plates.

### Actual behavior

Since undeads just have a mob teleporting them, the mob activates the pressure plate instead of the player.

### Steps to reproduce

Stand on a locked pressure plate as an undead

### Minecraft version and OS

1.18.1, Windows 10

### Checks

- [X] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

_No response_

### LINKED ISSUE #71: Undeads can easily switch morphs
### Expected behavior

Undeads shouldn't be able to rechoose their morph upon relogging.

### Actual behavior

Undeads can combat log by relogging which makes them go into the morph selection screen. This also lets them easily switch morphs in the middle of a battle (need range, switch to skeleton. Close quarters, use zombie).

### Steps to reproduce

1. Be undead
2. Log out
3. Log in
4. You can rechoose your morph

### Minecraft version and OS

1.18.1, Windows 10

### Checks

- [X] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

_No response_

### LINKED ISSUE #88: Make "list" configs in separate `lists.yml`
### What and How?

A separate file called `list.yml` that will have configs for all the different list stuff.
**List configs:**
- `settings.banned-words`
- `settings.lockable-blocks`
- `settings.disabled-commands`

### Why?

The `config.yml` file is pretty long cause of the 3 different lists inside of it.

### Are there alternatives?

- Moving all the `settings` options into a separate `settings.yml` file
- Making a separate file for each list

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

_No response_

### LINKED ISSUE #93: Display rank in Discord chat
### What and How?

Display the team prefix in the Discord channel when a player sends a message.
Example:
`OWNER CommandGeek » message`

### Why?

Just a nice touch

### Are there alternatives?

No

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

Would probably be easier/best if https://github.com/commandgeek/geeksmp/issues/57 was done first.

### LINKED ISSUE #94: Locked pressure plates can be activated by items
### Expected behavior

Locked pressure plates should only be activatable by the user which locked them.

### Actual behavior

Locked pressure plates can be activated by items

### Steps to reproduce

1. Place a pressure plate
2. Let another person lock it
3. Throw an item in the pressure plate

### Minecraft version and OS

_No response_

### Checks

- [X] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

_No response_

### LINKED ISSUE #95: `/trash`
### What and How?

A `/trash` command that will open an empty "chest" GUI. When the GUI is closed, all the items placed inside of it are deleted.
Only usable by staff.

### Why?

Super useful to quickly get rid of items if we are restoring someone's inventory or something.

### Are there alternatives?

- Flint and steel
- Placing the items in the inventory restore GUI (does the same thing as `/trash` would)

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

_No response_

### LINKED ISSUE #96: Remember `/bypass`
### What and How?

If `/bypass` is enabled, keep it enabled when user relogs.

### Why?

Annoying to redo the command every time we rejoin.

### Are there alternatives?

Another command, `/alwaysbypass` that will automatically enable bypass every time the user joins.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by srnyx**
## Description
- Reworked morph system a bit, it's now more flexible
  - Merged `Morph.java` into `MorphManager.java`
  - Added a persistent morphed data file
    - Fixes #71
- Simplified a bunch of code
- Added unbreakable attribute to `ItemManager.java`
- Adjusted skeleton bow/arrow
  - Made bow/arrow stay in specific slots
  - Gave bow/arrow Curse of Vanishing
  - Gave bow Infinity, Power 1, & unbreakable tag
  - Gave bow/arrow custom names & lores
  - Bow/arrow now removed on revive
  - Fixes #37
- Moved `onRespawn` event from `EventListener.java` to `DeathListener.java
- Added `/debug` for simple sub-commands to debug stuff
- Added `/trash` to quickly get rid of items
  - Fixes #95
- Players are now invulnerable to other players when AFKed
  - Added an option (`settings.afk-invulnerable`) in `config.yml` to toggle this
  - Fixes #56
- Renamed package from `com.commandgeek.GeekSMP` to `com.commandgeek.geeksmp` cause most stuff don't like capitals
- Added more code comments
- Adjusted `config.yml` comments
- Made `data/bypass.yml` to remember `/bypass` toggle
- Moved method `MorphManager.effect` into `MorhManager.morph`
- Made a new `lists.yml` config file for config options that are long lists
  - Fixes #88 
- Removed `revived-warning` which was given to revived players on-join
  - It's no longer valid/needed/used
- Made swears blocked out by using `&k`
  - They're blocked in Discord using `*`
  - Fixes #8 
- Prefixes set will take effect everywhere (instead of defining in multiple places)
- Added more `groups` settings
  - Added `groups.<group>.chat-color` to `config.yml` to set a chat color
  - Added `%prefix%` placeholder/setting for groups
  - `chat-format` was added to `messages.yml` for a universal format
  - Fixes #57 
- Improved the handling of potion effects for undead
  - Undeads can now use milk buckets
  - Fixes #51 
- You can now use `%prefix%` in `smp-chat-message`
  - Fixes #93 
- Entities can no longer trigger locked blocks
  - Fixes #70
  - Fixes #94 
- Added a `bypass.yml` data file to remember `/bypass`
  - Fixes #96
- Undead morphs can no longer be renamed using name tags
- Greatly improved `TabCompleter` handling
- Corrected a typo in `CommandReason.java`
  - Fixes #11
- Organized `messages.yml`
- Added `getList` method to `Setup.java` which will contain lists of similar blocks
- Added target support for `/trustlist`
  - Only usable by staff/ops
  - Fixes #15
- Added pets back as a config option (`settings.pets` in `config.yml`)
- Removed assertions (`assert X != null;`) as they apparently don't even do anything
- Prevented undeads from breaking minecarts since they can't even place them
- Added a `/day` and `/night` command that also works in console
- Added support for `%prefix%` in join/leave messages
- Added some code that was going to be used but doesn't need to be anymore
  - Keeping commented out in the plugin in-case it becomes useful in the future
- Added `/echest` command for staff to view/manipulate other player ender chests
- Improved anti-elytra/glide for undead

## Motivation and Context
1. Fixes #8
2. Fixes #11
3. Fixes #15
2. Fixes #37 
3. Fixes #51
2. Fixes #56 
3. Fixes #57
4. Fixes #70 
3. Fixes #71 
4. Fixes #88
5. Fixes #93
6. Fixes #94 
4. Fixes #95 
5. Fixes #96 

## How Has This Been Tested?
Tested on GeekSMP Development server.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to [the documentation](https://github.com/commandgeek/geeksmp/wiki).
- [x] I have read the [**CONTRIBUTING**](https://github.com/commandgeek/geeksmp/blob/master/.github/CONTRIBUTING.md) document.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by srnyx** [comment]
Need to find a way to move items already existing in the bow/arrow slots (unless it's the bow/arrow). Don't wanna delete people's swords.

**Comment by Lianecx** [comment]
People can use /afk in combat to make themselves invulnerable

**Comment by srnyx** [comment]
> other _small_ changes, you revamped the entire morph system -_-

> - Reworked morph system a bit, it's now more flexible

**Comment by Lianecx** [comment]
I was talking about the title. Its not fitting

**Comment by srnyx** [comment]
> I was talking about the title. Its not fitting

I reworked the morph system to fix #37 and #71

**Review by commandgeek — APPROVED** [review]

**Pull request merged**
