### PR TITLE
`/ip`, riptide undead fix, disabled commands in config

### LINKED ISSUE #54: Riptide does not work right with undeads
### Expected behavior

When using riptide as undead it will work just like normal, as it would with an alive.

### Actual behavior

The undead player takes damage from the trident mid-air stopping the riptide.

### Steps to reproduce

1. Be undead
2. Have Riptide trident
3. Use riptide trident mid air
4. Observer that you take damage mid air and fall

https://youtu.be/RKE3HBLtves

### Minecraft version and OS

1.17.1, Windows 10

### Checks

- [X] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

_No reponse_

### LINKED ISSUE #74: Add disabled commands to config
### What and How?

Make the list of disabled commands configurable in config.

### Why?

To add/remove commands you need to edit the code of the plugin.

### Are there alternatives?

Editing the code and then updating the plugin.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

Reference: https://github.com/commandgeek/geeksmp/blob/8cd9daea1987ebaed365cc10bc841608786b2d36/src/main/java/com/commandgeek/GeekSMP/listeners/CommandListener.java#L25

### LINKED ISSUE #77: `/ip`
### What and How?

A `/ip` command that will return the specified user's IP address.

### Why?

So we can easily detect alts.

### Are there alternatives?

Looking at the join logs. We'll get the same result, just takes longer.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by Lianecx**
## Description
Tridents now work properly for undeads (no damage anymore)
Disabled commands can now be set in the config.yml (settings.disabled-commands)
/ip command added (shows public ip address of player)

## Motivation and Context
fixes #54
fixes #77
fixes #74

## How Has This Been Tested?
Local hosted server
MC Version 1.17.1, Paper

- Executed disabled commands
- Tried to riptide with a trident as an undead and revived
- Executed /ip command for myself and another player who joined

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
-  [x] My code follows the code style of this project.
- [ ] My change requires a change to [the documentation](https://github.com/commandgeek/geeksmp/wiki).
- [x] I have read the [**CONTRIBUTING**](https://github.com/commandgeek/geeksmp/blob/master/.github/CONTRIBUTING.md) document.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Lianecx** [comment]
Is the `/ip` response message fine or should it be something else?

Currently it's: "The IP of Lianecx is 127.0.0.1"

**Comment by srnyx** [comment]
> Is the `/ip` response message fine or should it be something else?
> 
> Currently it's: "The IP of Lianecx is **127.0.0.1**"

Could you make it configurable in `messages.yml`?

**Comment by Lianecx** [comment]
Sure, ill make it work with messages, 
I removed unnecessary code in /afk. Both if statements that i removed are already there, above the cooldown checker
I replace the "/" and the "minecraft:" (if it exists) of the command that the user types so you only have to specify "help" in the config and not both "help" AND "minecraft:help"

**Comment by Lianecx** [comment]
There are no command response messages inside messages.yml

**Comment by Lianecx** [comment]
Under which category should i add the message

**Comment by srnyx** [comment]
> I replace the "/" and the "minecraft:" (if it exists) of the command that the user types so you only have to specify "help" in the config and not both "help" AND "minecraft:help"

That may cause some issues though. The plugin overwrites the `/tp` command which means if we wanna use selectors or the vanilla command we type `/minecraft:tp`.

**Comment by srnyx** [comment]
> Under which category should i add the message

`Information Messages`

**Review by srnyx — APPROVED** [review]

**Pull request merged**
